name: Frontend Deployment Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Stap 1: Checkout de repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Stel Node.js in
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      # Installeer dependencies
      - name: Install Dependencies
        run: |
          npm install

      # Run Linter
      - name: Run ESLint
        run: |
            npx eslint . || exit 1

      # Run Unit Tests
      - name: Run Unit Tests
        run: |
          npm test

      # Build de frontend
      - name: Build Frontend Application
        run: |
          npm run build

      # Deploy met Docker
      - name: Build and Run Frontend with Docker Compose
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d
