name: Frontend Code Quality and Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout de repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Stel Node.js in
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      # Installeer frontend dependencies
      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      # Run Linter
      - name: Run ESLint
        run: |
          cd frontend
          npx eslint . --ext .js,.svelte || exit 1

      # Run Unit Tests
      - name: Run Unit Tests
        run: |
          cd frontend
          npm test
