name: Frontend Code Quality and Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout de repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Stel Node.js in
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'

      # Installeer frontend dependencies
      - name: Install Dependencies
        run: |
          npm install

      # Run Linter
      - name: Check for ESLint configuration
        run: |
          # Check if eslint.config.js exists, if not create a default configuration
          if [ ! -f eslint.config.js ]; then
            echo 'export default [
              {
                rules: {
                  semi: "error",
                  "prefer-const": "error",
                  "no-unused-vars": "warn",
                  "no-console": "warn"
                }
              }
            ];' > eslint.config.js
          fi

          - name: Run ESLint
          run: |
            # Check if source directory exists
            if [ -d src ]; then
              echo "Linting the project..."
              npx eslint src --max-warnings=0
            else
              echo "Directory 'src' does not exist. Please verify your project structure."
              exit 1
            fi

      # Run Unit Tests
    #  - name: Run Unit Tests
     #   run: |
      #    npm test
