name: GitHub Actions Pipeline
run-name: ${{ github.actor }} is testing GitHub Actions 🚀

on:
  push:
  pull_request:

permissions:
  contents: read    # Minimum required to check out code
  packages: read    # Minimum required for accessing packages (if necessary)
  statuses: write   # To report job statuses

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    name: Build and Test Job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.13' # Updated to meet dependency requirements

      - name: Install dependencies
        run: npm install
        env:
          CI: true

      - name: Build application
        run: npm run build

      - name: Manage environment parameters (for 3.1)
        run: |
          echo "DATABASE_URL=$DATABASE_URL" >> .env
          echo "API_KEY=$API_KEY" >> .env
          cat .env

      - name: Deploy application (Optional)
        run: |
          echo "Deploying application..."

      - name: Dockerize application (Containerization for 2.4)
        run: |
          docker build -t my-app .
          docker tag my-app:latest my-dockerhub-user/my-app:latest
          echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
          docker push my-dockerhub-user/my-app:latest
