name: GitHub Actions Pipeline
run-name: ${{ github.actor }} is testing GitHub Actions 🚀

on:
  push:
  pull_request:

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    name: Build and Test Job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          echo "Docker is already installed on the GitHub-hosted runner."

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Run container for testing
        run: docker run --rm my-app npm test

      - name: (Optional) Run the container locally
        run: |
          echo "Run the container locally for manual testing."
          docker run --rm -p 3000:3000 my-app
