name: GitHub Actions Pipeline
run-name: ${{ github.actor }} is testing GitHub Actions 🚀

on:
  push:
  pull_request:

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  Build-Test-Lint:
    runs-on: ubuntu-latest
    name: Build, Test, and Lint Job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          echo "Docker is already installed on the GitHub-hosted runner."

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Run container for testing
        run: docker run --rm my-app npm test

      - name: Run container for linting
        run: docker run --rm my-app npm run lint
