name: GitHub Actions Pipeline
run-name: ${{ github.actor }} is testing GitHub Actions 🚀

on:
  push:
    branches:
      - main
      - pipeline
  pull_request:
    branches:
      - main

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install minimal dependencies
        run: npm install

      # Step 4: Run the build process
      - name: Build the software
        run: npm run build

      # Step 5: notify via Email(SendGrid) on failure
      - name: Send Email Notification
  if: failure()
  uses: dawidd6/action-send-mail@v3
  with:
    server_address: smtp.sendgrid.net
    server_port: 587
    username: apikey
    password: ${{ secrets.SENDGRID_API_KEY }}
    subject: 'Build Failed - CI/CD Pipeline'
    body: 'The pipeline failed. Please check the logs at: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
    to: nitaifechukwu@gmail.com
    from: ci-pipeline@example.com


      # Step 6: Notify on failure using GitHub PR comments
      - name: Comment on pull request (on failure)
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ github.event.pull_request.number }},
              owner: '${{ github.repository_owner }}',
              repo: '${{ github.event.repository.name }}',
              body: `
              🚨 Build Failed for branch *${{ github.ref_name }}*.
              Please check the logs and resolve the issues.
              Workflow: *${{ github.workflow }}*
              Job Status: *${{ job.status }}*
              `
            });

      # Step 7: Log success
      - name: Log success message
        if: success()
        run: echo "✅ Build and tests completed successfully!"