name: GitHub Actions Pipeline
run-name: ${{ github.actor }} is testing GitHub Actions 🚀

on: 
  push:
    branches:
      - main
      - pipeline
  pull_request:
    branches:
      - main

jobs:
  Build-and-Test:
    runs-on: ubuntu-24.10

    steps:
      # Step 1: Check out the repository
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Set up the necessary environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the build process
      - name: Build the software
        run: npm run build

      # Step 5: Run automated tests
      - name: Run tests
        run: npm test

      # Step 6: Provide feedback
      - run: echo "✅ Build and tests completed successfully!"
