name: GitHub Actions Pipeline
run-name: ${{ github.actor }} is testing GitHub Actions 🚀

on:
  push:
    branches:
      - main
      - pipeline
  pull_request:
    branches:
      - main

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the build process
      - name: Build the software
        run: npm run build

      # Step 5: Run tests
      - name: Run tests
        run: npm test -- --watchAll=false

      # Step 6: Notify on failure (if build fails on push)
      - name: Post a comment or create issue on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const { github, context } = require('@actions/github');

            if (context.payload.pull_request) {
              // Handle PR event and post comment
              github.rest.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `🚨 Build failed for branch: *${context.ref}*. Please check the logs.`
              });
            } else {
              // Handle push event and create an issue if not a PR
              github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `🚨 Build failed for branch: *${context.ref}*`,
                body: `The build failed for the branch: *${context.ref}*. Please check the logs.`
              });
            }

      # Step 7: Log success message
      - name: Log success message
        if: success()
        run: echo "✅ Build and tests completed successfully!"
