name: GitHub Actions Pipeline
run-name: ${{ github.actor }} is testing GitHub Actions 🚀

on:
  push:
  pull_request:

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  Build-Test:
    runs-on: ubuntu-latest
    name: Build, Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Manage environment parameters
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          cat .env
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          API_KEY: ${{ secrets.API_KEY }}

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Run container for testing
        run: docker run --rm my-app npm test

      - name: Run unit tests
        run: npm test
        env:
          CI: true

      - name: Lint codebase
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
