name: NodeJS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Build
<<<<<<< HEAD
      run: npm install --legacy-peer-deps
=======
      run: |
        npm install
>>>>>>> cb44008 (added eslint to the pipeline and removed a package in the json file so now npm install works correctly)
    
    - name: Run build
      run: npm run build

    - name: Run Test
      run: npm run test
        
