name: Deploy SvelteKit App

on:
  push:
    branches:
      - main
      - unitTesting

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install
        continue-on-error: false
        # run: |
        #   npm install
        #   # Simulate an error here
        #   echo "Simulating error in npm install"
        #   exit 1  # This will cause the build to fail

      # Step 5: Build the SvelteKit Application
      - name: Build Application
        run: npm run build
        continue-on-error: false  # Halt if build fails

      # Step 4: Build the SvelteKit Application
      - name: Build Application
        run: npm run build
        continue-on-error: false

      # Step 5: Deploy to Hosting (Vercel example)
      - name: Deploy to Vercel
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --yes
        continue-on-error: false