name: Build and Test Svelte Application

on: 
  push:
    branches:
      - "**"  # Trigger op elke push naar elke branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build the Svelte application
        run: npm run build

      # Maak een GitHub Issue bij mislukking
      - name: Create GitHub Issue on failure
        if: failure()  # Dit zorgt ervoor dat de stap alleen wordt uitgevoerd als de build faalt
        uses: peter-evans/create-issue-from-file@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Dit is de token waarmee GitHub acties toegang krijgen tot de repository
          title: "Build Failure - Svelte Application"
          body: |
            The build for the Svelte application has failed.
            Please investigate the error.
