name: Build and Test Svelte Application

on: 
  push:
    branches:
      - "**"  # Trigger bij elke push naar elke branch

jobs:
  build:
    runs-on: ubuntu-latest # Het buildproces wordt op een volledig geconfigureerde server uitgevoerd

    steps:
      # 1. Haal de laatste code op
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Installeer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Zorg voor de juiste versie van Node.js

      # 3. Installeer dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Voer het buildproces uit
      - name: Build the Svelte application
        run: npm run build

      # Debug output
      - name: Debug output
        run: echo "Debug: Build step failed"
      
      # Stap om automatisch een issue aan te maken bij falen van de build
      - name: Create issue on failure
        if: failure()  # Alleen uitvoeren als de build mislukt
        uses: peter-evans/create-issue@v3
        with:
          title: "🚨 Build failed for ${{ github.ref }}"
          body: |
            The build for branch `${{ github.ref }}` has failed. Please check the logs for more details.
            - Build logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          labels: "bug, build-failure"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
