name: Build and Test Svelte Application

on:
  push:
    branches:
      - "**"  # Trigger bij elke push naar elke branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build the Svelte application
        run: npm run build

      # Stap om automatisch een issue aan te maken bij falen van de build
      - name: Create issue on failure
        if: failure()  # Alleen uitvoeren als de build mislukt
        uses: peter-evans/create-issue@v3
        with:
          title: "🚨 Build failed for ${{ github.ref }}"
          body: |
            The build for branch `${{ github.ref }}` has failed. Please check the logs for more details.
            - Build logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          labels: "bug, build-failure"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
