name: Build and Test Svelte Application

on: 
  push:
    branches:
      - "**"  # Trigger op elke push naar elke branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build the Svelte application
        run: npm run build

      # Maak een GitHub Issue bij mislukking
      - name: Create issue when build fails
        if: failure()
        run: |
          echo "The build has failed for the Svelte application." > issue-content.txt
          echo "Please investigate the error in the GitHub Actions logs." >> issue-content.txt
          echo "Failure details: ${{ github.run_id }}" >> issue-content.txt

      # Maak een GitHub Issue met de inhoud uit het bestand
      - name: Create GitHub Issue from file
        if: failure()
        uses: peter-evans/create-issue-from-file@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Build Failure - Svelte Application"
          content-filepath: issue-content.txt
